# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
