# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20160401_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_admin',
            field=models.ManyToManyField(blank=True, null=True, to='bbs.UserInfo'),
        ),
    ]
