# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20160428_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='manufactory',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manufactory',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='newassetapprovalzone',
            old_name='manufactory',
            new_name='manufacturer',
        ),
    ]
