# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('privilege', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
    ]
