# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=25)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(max_length=5)),
                ('group', models.CharField(max_length=25, verbose_name='\u4e3b\u673a\u7ec4')),
                ('description', models.CharField(default='nothing...', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupRelevance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.HostGroup')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Host')),
            ],
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='group_member',
            field=models.ManyToManyField(through='search.HostGroupRelevance', to='search.Host'),
        ),
    ]
