# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='group',
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=80),
        ),
    ]
