# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20)),
                ('business_ip', models.CharField(max_length=15)),
                ('manage_ip', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
